# Generated by Django 5.0.1 on 2024-01-10 13:20

import django.contrib.postgres.indexes
import django.db.models.deletion
import urlshortener.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='URLMapRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=urlshortener.utils.generate_key, editable=False, max_length=6, unique=True)),
                ('target', models.URLField(verbose_name='target URL')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'URL map record',
                'verbose_name_plural': 'URL map',
                'indexes': [django.contrib.postgres.indexes.HashIndex(fields=['key'], name='urlshortene_key_d7e1da_hash'), models.Index(fields=['creation_date'], name='urlshortene_creatio_c0c997_idx')],
            },
        ),
    ]
